### PR TITLE
#12 - adding rsWebDeploy tool (modified from MS version)

### PR DESCRIPTION
**Pull request by RSabounds**

### CODE REVIEW

**Comment by jonathan-madison** [comment]
Alan, please elaborate on this one as well for visibility.

Thanks!

**Comment by RSabounds** [comment]
This configuration change moves from the msWebDeploy included in the msWebAdministration to the rsWebConfiguration module.
reason: avoiding conflict with msWebAdministration module, which may change, but could not discover easy method to publish recommendation back to Microsoft module.
fixes: msWebDeploy module incorrectly attempts to distinguish file-path & site-names, resulting in a module that can only deploy if the site in question is a named site, without a sub-site application path, and said site has no spaces in the name.
The new version is still subject to the space limitation today, but allows for a site-name, sub-application name (containing '\'), or directory path (containing ':' & '\'). The tool will then deploy the site from a webdeploy package to the specified folder for the site.

**Comment by RSabounds** [comment]
saw this is still pending merge-request.

**Comment by RSabounds** [comment]
closing pull request. there is another issue in this module that needs addressed. will re-open with both fixes in place.

**Pull request closed without merging**
